### PR TITLE
Add HTML report

### PR DESCRIPTION
**Pull request by mcwitt**
Addresses #44 

- [x] Summary plots
  - [x] relative free energy distribution
  - [x] cumulative distribution
- [x] RUN info
  - [x] RUN number
  - [x] DDG
  - [x] DDG 95% CI
  - [x] work distributions (thumbnail for top 20, links to png and pdf files)
  - [x] convergence plot (thumbnail, links)
  - [x] SMILES? Molecule thumbnail?

#### Sample output
image
image

### CODE REVIEW

**Comment by jchodera** [comment]
Jinja templates! Yay!

**Comment by jchodera** [comment]
Wow, this is amazing!

The most important modifications, in order, are:
* Add links to download `compounds.{pdf,csv,sdf}` and `proteins.pdb` generated by the code in `postprocess.py`, since these will be important for inspection
* Add the molecule `title` to the rows (in addition to the `RUN`) since this is the most critical information for the chemists
* Until we change to solving for absolute free energies (#52), we should display the free energy difference as "ΔΔG (kcal/mol)" and show "X ± Y" where Y is one standard error, or "X [W, Z]" where [W, Z] represents the 95% CI
* If you can insert images in the table, but if so, you can use [this idiom](https://docs.eyesopen.com/toolkits/cookbook/python/depiction/transparent.html) to generate images of the molecules from the SMILES strings using the `openeye-toolkit` conda package installed from the `openeye` channel. I believe this is already installed (along with the license file) in the `perses` environment. (Ask if you need a local copy!)
* If we can add links to each row to the SDF and PDB files for molecule and protein in `structures/`, that would be awesome

Later, we can make this fancy and interactive!

**Comment by hannahbrucemacdonald** [comment]
This is awesome!!!

Some minor points:
- Maybe I'm stupid but what's UB? upper bound?
- I'd personally prefer to have kcal/mol everywhere, including the table, but I'm happy to be ignored
- Molecule thumbnail would be great, I can write a function for you if you want me to generate a .pdf of the ligand structure
- 3 decimal places might be overkill

**Comment by jchodera** [comment]
> Maybe I'm stupid but what's UB? upper bound?

We should eliminate that column and just have the `X ± Y` or `X [Y, Z]` 95% CI format.

> I'd personally prefer to have kcal/mol everywhere, including the table, but I'm happy to be ignored

Let's use kcal/mol in all the plots for now. The chemists think in these units.
Later, after we integrate DiffNet (#52), we can also generate versions that show the Kd (in M, for Molar) on a log scale, so that we can show whether we expect pM, nM, µM, etc.

> 3 decimal places might be overkill

The appropriate way to represent uncertainty in `X ± Y` format is to report one sig fig of the standard error `Y` and then report `X` to the same number of decimal places, e.g.:
```
1.234 ± 0.002
1.23 ± 0.04
1.2 ± 0.3
5 ± 1
```
but not
```
1.234 ± 0.023
1.23 ± 0.17
```
For the 95% CI, we just need enough sig figs for the CI numbers to be distinct in how they are represented:
```
1.23 [1.20, 1.24]
```
but not
```
1.231 [1.201, 1.247
```
There's a useful package that helps with this:
https://pythonhosted.org/uncertainties/

but [pint](https://pint.readthedocs.io/en/stable/) or [unyt](https://unyt.readthedocs.io/en/stable/) may have similar capabilities.

**Comment by jchodera** [comment]
Whoops, we should also get the SMILES string in each row.

**Comment by mcwitt** [comment]
@jchodera @hannahbrucemacdonald 
> Add the molecule title to the rows (in addition to the RUN) since this is the most critical information for the chemists

> you can use this idiom to generate images of the molecules from the SMILES

> Molecule thumbnail would be great

Dumb question: each RUN includes 2 sets of `title` and `smiles` (`start` and `end`). Do we want to display one or the other or both in the table?

**Comment by mcwitt** [comment]
@hannahbrucemacdonald 

> what's UB? upper bound?

Yes, I originally had the idea to sort by upper bound of the CI to avoid bad estimates floating to the top (but this doesn't seem to be too much an issue). I'm in the process of changing this to standard error format (X ± Y).

**Comment by jchodera** [comment]
Also, this seems silly, but can we change the font to something sans serif? Maybe one of the free [Google fonts](https://developers.google.com/fonts) (instructions on including them are [here](https://developers.google.com/fonts/docs/getting_started))?

Type specimens are [here](https://fonts.google.com/). [Roboto](https://fonts.google.com/specimen/Roboto) is pretty common, or [Alata](https://fonts.google.com/specimen/Alata?preview.text=COVID+Moonshot+Sprint+3+Analysis+Summary+CID+free+energy+of+binding+%CE%94%CE%94G+%2F+kcal+mol&preview.text_type=custom) if we want to be extra special.

**Comment by hannahbrucemacdonald** [comment]
Erm, so at the moment when we are sorting by RUNS I think we only want the ‘old’ molecule, but when we move to more complicated networks of graphs I think we would want to not report on a RUN but have a row for each ligand (so only one ligand shown still)

Maybe we could chat about getting the more complicated graph analysis (DiffNet) into the pipeline soon?

Ha I was surprised that John hadn’t commented on the font... 😂

**Comment by jchodera** [comment]
> Erm, so at the moment when we are sorting by RUNS I think we only want the ‘old’ molecule, but when we move to more complicated networks of graphs I think we would want to not report on a RUN but have a row for each ligand (so only one ligand shown still)

Yes! So after #32 -> #52 get integrated, we will want to split up the table into three tables: (1) compounds, (2) molecules, and (3) transformations, matching the new JSON format.

Compounds will have 
* Compound ID (CID)
* compound image
* reference SMILES for the compound
* predicted absolute free energy (ΔG = -7.23 [-7.29, -7.20] kcal/mol)
* predicted affinity (Kd = 4.9 [2.3, 10.4] µM)
* link to structure snapshots?

Molecules will have 
* Molecule ID (MID)
* Compound ID (CID)
* molecule image
* SMILES for the specific molecule state
* predicted absolute free energy (ΔG = -7.23 [-7.29, -7.20] kcal/mol)
* predicted affinity (Kd = 4.9 [2.3, 10.4] µM)
* link to structure snapshots?

Transformations will have
* RUN ID
* old/new MIDs
* predicted relative free energy (ΔΔG = -1.23 [-1.29, -1.20] kcal/mol)
* work plots
* convergence plots
* link to structure snapshots?

> Maybe we could chat about getting the more complicated graph analysis (DiffNet) into the pipeline soon?

Can you set that up @hannahbrucemacdonald ? Happy to join if it would help!

**Comment by jchodera** [comment]
Looking great!

The only issue I spotted was a logic error in sig figs: `-0.8 ± 0.08` isn't correct since it should have one more sig fig in the -0.8 quantity.

**Comment by jchodera** [comment]
Let's also show the whole CDF so we get a sense for the fraction that score well!

Also, great font!

**Comment by mcwitt** [comment]
> Let's also show the whole CDF so we get a sense for the fraction that score well!

This should be the case already (the sample was run on my local machine with a small fraction of the runs)

**Pull request merged**
